# Generated by Django 4.0.3 on 2022-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XKCDComicViews",
            fields=[
                (
                    "comic_number",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("view_count", models.IntegerField(default=0)),
            ],
        ),
    ]
